// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAND3EbDitkQDWx-uXxdS9OZ2yd29twk',
    appId: '1:896308618203:web:09d0cfaecae06030f6fdfe',
    messagingSenderId: '896308618203',
    projectId: 'one-for-twelve-32778',
    authDomain: 'one-for-twelve-32778.firebaseapp.com',
    storageBucket: 'one-for-twelve-32778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFtNXcuz5US0T5J6wOSEppqCJglipN4o',
    appId: '1:896308618203:android:1241593d8a7d4491f6fdfe',
    messagingSenderId: '896308618203',
    projectId: 'one-for-twelve-32778',
    storageBucket: 'one-for-twelve-32778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHOXYwF02bJ8KbtfJo6cmWDKfXNrLu4EU',
    appId: '1:896308618203:ios:cb89fdb43985b454f6fdfe',
    messagingSenderId: '896308618203',
    projectId: 'one-for-twelve-32778',
    storageBucket: 'one-for-twelve-32778.appspot.com',
    androidClientId: '896308618203-38afo5rt980cpf0cn4p7roiguhqqrta5.apps.googleusercontent.com',
    iosClientId: '896308618203-36agrfena93gc46heuhva43chrhdhvv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneForTwelve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHOXYwF02bJ8KbtfJo6cmWDKfXNrLu4EU',
    appId: '1:896308618203:ios:cb89fdb43985b454f6fdfe',
    messagingSenderId: '896308618203',
    projectId: 'one-for-twelve-32778',
    storageBucket: 'one-for-twelve-32778.appspot.com',
    androidClientId: '896308618203-38afo5rt980cpf0cn4p7roiguhqqrta5.apps.googleusercontent.com',
    iosClientId: '896308618203-36agrfena93gc46heuhva43chrhdhvv2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneForTwelve',
  );
}
